# Generated by Django 3.0.7 on 2020-11-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('order', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_chats', to=settings.AUTH_USER_MODEL)),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
